name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Debug
        run: ./gradlew assembleDebug

      - name: Check Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Check style
        run: ./gradlew detekt

      - name: Check lint
        run: ./gradlew lint

    unit-tests:
      name: Unit tests
      runs-on: ubuntu-latest
      timeout-minutes: 120
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17
        - uses: gradle/actions/setup-gradle@v4
          continue-on-error: true
          timeout-minutes: 5
          with:
            cache-overwrite-existing: true
            gradle-home-cache-cleanup: true

        - name: Unit tests
          run: ./gradlew testDebugUnitTest validateDebugScreenshotTest verifyRoborazziDebug compareRoborazziDebug verifyRoborazziDebug validateDebugScreenshotTest

    instrumentation-tests:
      name: Instrumentation tests
      runs-on: ubuntu-latest
      timeout-minutes: 60
      strategy:
        fail-fast: true
        matrix:
          api-level: [33, 34, 35]
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17
        - uses: gradle/actions/setup-gradle@v4
          continue-on-error: true
          timeout-minutes: 5
          with:
            cache-overwrite-existing: true
            gradle-home-cache-cleanup: true

        # API 30+ emulators only have x86_64 system images.
        - name: Get AVD info
          uses: ./.github/actions/get-avd-info
          id: avd-info
          with:
            api-level: ${{ matrix.api-level }}

        - name: Enable KVM
          run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm

        - name: Instrumentation tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: ${{ matrix.api-level }}
            arch: ${{ steps.avd-info.outputs.arch }}
            target: ${{ steps.avd-info.outputs.target }}
            script: ./gradlew connectedDebugAndroidTest
