name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradle wrapper cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradlewrapper

      - name: Run check
        run: ./gradlew detekt --profile --daemon

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradle wrapper cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradlewrapper

      - name: Lint
        run: ./gradlew lint

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: '35.0.0'
          ndk: '25.2.9519653'

      # Build and run tests
      - name: Build and run tests
        run: ./gradlew build test

  #      - name: Run screenshot test
  #        run: ./gradlew validateDebugScreenshotTest
  #      - name: Upload build reports
  #        uses: actions/upload-artifact@v4
  #        if: always()
  #        with:
  #          name: artifact
  #          path: app/build/reports

#  store-screenshots:
#    runs-on: macos-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3.9.0
#        with:
#          distribution: 'zulu'
#          java-version: 17
#
#      - name: Gradle cache
#        uses: gradle/gradle-build-action@v2
#
#      - name: test
#        run: |
#          # Create screenshots
#          ./gradlew app:recordRoborazziDebug --stacktrace
#
#      # Upload screenshots to GitHub Actions Artifacts
#      - uses: actions/upload-artifact@v3
#        with:
#          name: screenshots
#          path: app/build/outputs/roborazzi
#          retention-days: 30
#
#  verify-screenshots:
#    runs-on: macos-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3.9.0
#        with:
#          distribution: 'zulu'
#          java-version: 17
#
#      - name: Gradle cache
#        uses: gradle/gradle-build-action@v2
#
#      # Download screenshots from main branch
#      - uses: dawidd6/action-download-artifact@v2
#        with:
#          name: screenshots
#          path: app/build/outputs/roborazzi
#          workflow: test.yaml
#          branch: main
#
#      - name: verify test
#        id: verify-test
#        run: |
#          # If there is a difference between the screenshots, the test will fail.
#          ./gradlew app:verifyRoborazziDebug --stacktrace
#
#      - uses: actions/upload-artifact@v3
#        if: ${{ always() }}
#        with:
#          name: screenshot-diff
#          path: app/build/outputs/roborazzi
#          retention-days: 30
#
#      - uses: actions/upload-artifact@v3
#        if: ${{ always() }}
#        with:
#          name: screenshot-diff-reports
#          path: app/build/reports
#          retention-days: 30
#
#      - uses: actions/upload-artifact@v3
#        if: ${{ always() }}
#        with:
#          name: screenshot-diff-test-results
#          path: app/build/test-results
#          retention-days: 30
